os: windows
language: shell
branches:
  only:
  - master
script:
- choco pack lazydocker\\lazydocker.nuspec
after_script:
- choco apikey --key $CHOCOAPIKEY --source https://push.chocolatey.org/
- choco push
